import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { importDemoPack } from "../src/server/content-import";
import { openDatabase } from "../src/server/db";
import { correctManualEvidence, publishManualEvidence, saveManualDraft } from "../src/server/evidence-store";
import { loadObservations } from "../src/server/learning-store";
import { chooseItem, createSession, recordAssistance, submitAttempt } from "../src/server/session-store";
import { summarizeLearning } from "../src/domain/learning";

test("synthetic setup, supported practice, independent item and reviewed manual evidence persist", () => {
  const dir = mkdtempSync(join(tmpdir(), "learnpilot-flow-"));
  const file = join(dir, "data.sqlite");
  let db = openDatabase(file);
  try {
    importDemoPack(db);
    const now = new Date().toISOString();
    db.prepare("INSERT INTO students (id, display_name, environment, goal, created_at, updated_at) VALUES ('demo:student:local', 'Demo', 'synthetic_demo', 'practice', ?, ?)").run(now, now);
    const first = createSession(db, "demo:units", "practice", "Test support")!;
    recordAssistance(db, first, "hint");
    const attemptId = submitAttempt(db, first, "500 mA", "none", "stable-submit-1");
    assert.equal(submitAttempt(db, first, "500 mA", "none", "stable-submit-1"), attemptId);
    assert.equal((db.prepare("SELECT COUNT(*) AS n FROM attempts").get() as { n: number }).n, 1);
    assert.equal((db.prepare("SELECT assistance_status FROM attempts WHERE id = ?").get(attemptId) as { assistance_status: string }).assistance_status, "recorded_assisted");
    assert.equal(summarizeLearning(loadObservations(db, "demo:student:local", "demo:units")).observedResult, "supported_correct");
    const second = createSession(db, "demo:units", "practice", "New item")!;
    const secondPlan = db.prepare("SELECT evidence_refs_json, resource_id FROM study_plans WHERE id = (SELECT plan_id FROM sessions WHERE id = ?)").get(second) as { evidence_refs_json: string; resource_id: string };
    assert.deepEqual(JSON.parse(secondPlan.evidence_refs_json), [attemptId]);
    assert.equal(secondPlan.resource_id, "demo:resource:units");
    assert.equal(chooseItem(db, "demo:units", "reassessment")?.id, "demo:item:u05", "reserved item remains unseen during practice");
    submitAttempt(db, second, "0.25 A", "none", "stable-submit-2");
    const observations = loadObservations(db, "demo:student:local", "demo:units");
    assert.equal(observations.length, 2);
    assert.equal(summarizeLearning(observations).observedResult, "correct_item");
    const evidenceId = saveManualDraft(db, { conceptId: "demo:units", question: "Fictional conversion", response: "10 mA", teacherMark: "1/2", locator: "Demo sheet Q1", sourceDescription: "Fictional worksheet" });
    assert.equal(loadObservations(db, "demo:student:local", "demo:units").length, 2, "draft cannot affect progress");
    publishManualEvidence(db, evidenceId, "incorrect");
    assert.equal(summarizeLearning(loadObservations(db, "demo:student:local", "demo:units")).observedResult, "mixed");
    const marks = db.prepare("SELECT mark, teacher_mark, mark_origin FROM evidence_revisions WHERE evidence_id = ?").get(evidenceId) as { mark: string; teacher_mark: string; mark_origin: string };
    assert.equal(marks.teacher_mark, "1/2");
    assert.equal(marks.mark, "incorrect");
    assert.equal(marks.mark_origin, "local_demo_user_review");
    const activeBeforeCorrection = createSession(db, "demo:units", "practice", "Plan awaiting correction")!;
    const oldRevision = (db.prepare("SELECT current_revision_id AS id FROM evidence WHERE id = ?").get(evidenceId) as { id: string }).id;
    const correction = { conceptId: "demo:units", question: "Fictional conversion, corrected", response: "200 mA", teacherMark: "1/2", locator: "Demo sheet Q1", sourceDescription: "Fictional worksheet" };
    const newRevision = correctManualEvidence(db, evidenceId, oldRevision, correction, "correct", "Transcription was corrected");
    assert.notEqual(newRevision, oldRevision);
    assert.equal(summarizeLearning(loadObservations(db, "demo:student:local", "demo:units")).observedResult, "correct_item");
    assert.equal((db.prepare("SELECT mark FROM evidence_revisions WHERE id = ?").get(oldRevision) as { mark: string }).mark, "incorrect", "historical review remains");
    assert.throws(() => correctManualEvidence(db, evidenceId, oldRevision, correction, "correct", "Stale tab edit"), /changed/);
    assert.equal((db.prepare("SELECT COUNT(*) AS n FROM study_plans WHERE status = 'stale'").get() as { n: number }).n, 3);
    assert.throws(() => submitAttempt(db, activeBeforeCorrection, "3000 Ω", "none", "stale-plan-submit"), /Active session not found/);
    db.close();
    db = openDatabase(file);
    assert.equal((db.prepare("SELECT COUNT(*) AS n FROM attempts").get() as { n: number }).n, 2);
    assert.equal(loadObservations(db, "demo:student:local", "demo:units").length, 3);
    assert.equal((db.prepare("SELECT COUNT(*) AS n FROM evidence_revisions WHERE evidence_id = ?").get(evidenceId) as { n: number }).n, 2);
  } finally { db.close(); rmSync(dir, { recursive: true, force: true }); }
});
