import type Database from "better-sqlite3";
import { subjectsFor } from "@/domain/family-catalog";
import { selectedLearner } from "@/server/learner";
import { redirect } from "next/navigation";
import { getDb } from "@/server/db";
import { correctEvidence, publishEvidence, saveEvidence } from "./actions";

export const dynamic = "force-dynamic";

function RevisionHistory({ db, evidenceId }: { db: Database.Database; evidenceId: string }) {
  const revisions = db.prepare("SELECT revision_number, response, mark, correction_reason, created_at FROM evidence_revisions WHERE evidence_id = ? ORDER BY revision_number DESC").all(evidenceId) as { revision_number: number; response: string; mark: string | null; correction_reason: string | null; created_at: string }[];
  if (revisions.length < 2) return null;
  return <details><summary>Review revision history</summary><ol>{revisions.map(revision => <li key={revision.revision_number}>Revision {revision.revision_number}: {revision.response} · {revision.mark ?? "unscored"} · {revision.correction_reason ?? "initial record"} · {revision.created_at}</li>)}</ol></details>;
}

export default async function EvidencePage() {
  const learner = await selectedLearner();
  if (!learner) redirect("/setup");
  const concepts = subjectsFor(learner.key).flatMap(group => group.concepts);
  const db = getDb();
  const rows = db.prepare(`SELECT e.id, e.status, e.source_description, r.id AS revision_id, r.revision_number, r.concept_id, r.question_text, r.response, r.teacher_mark, r.mark, r.source_locator, r.mark_origin
    FROM evidence e JOIN evidence_revisions r ON r.id = e.current_revision_id WHERE e.student_id = ? ORDER BY e.created_at DESC`)
    .all(learner.id) as { id: string; status: string; source_description: string | null; revision_id: string; revision_number: number; concept_id: string; question_text: string; response: string; teacher_mark: string | null; mark: string | null; source_locator: string; mark_origin: string }[];
  return <div className="page"><p className="eyebrow">Manual evidence · synthetic only</p><h1>Keep the work behind the conclusion.</h1><p className="lead">Enter a fictional assessment question and answer. A draft does not affect progress until you inspect and publish it. A transcribed teacher mark stays separate from your local demo review.</p>
    <form action={saveEvidence} className="form-card"><h2>New manual draft</h2><label>Question or task<textarea name="question" rows={3} required maxLength={1000} /></label><label>Recorded response<textarea name="response" rows={3} maxLength={2000} /></label><div className="form-row"><label>Topic<select name="conceptId">{concepts.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Question locator<input name="locator" placeholder="For example: practice page, Q3" required maxLength={200} /></label></div><div className="form-row"><label>Source description<input name="sourceDescription" placeholder="For example: fictional worksheet" maxLength={200} /></label><label>Teacher mark as written (optional)<input name="teacherMark" placeholder="Keep the original mark text" maxLength={100} /></label></div><button className="button" type="submit">Save draft</button></form>
    <h2 className="list-heading">Saved evidence</h2>{rows.length === 0 && <p className="muted">No manual evidence yet. Practice attempts will appear in Progress separately.</p>}
    <div className="evidence-list">{rows.map(row => <article className="feature-card" key={row.id}><span className="tag">{row.status} · revision {row.revision_number}</span><h3>{row.question_text}</h3><p><strong>Response:</strong> {row.response || "Not recorded"}</p><p className="muted">Source: {row.source_description || "manual entry"} · {row.source_locator} · {concepts.find(c => c.id === row.concept_id)?.title}</p><p className="muted">Teacher mark transcription: {row.teacher_mark || "none"} · Local review: {row.mark ?? "not assessed"} ({row.mark_origin})</p>
      {row.status === "draft" && <><details><summary>Edit this draft</summary><form action={saveEvidence} className="form-card compact-form"><input type="hidden" name="evidenceId" value={row.id} /><label>Question<textarea name="question" defaultValue={row.question_text} required rows={2} /></label><label>Response<textarea name="response" defaultValue={row.response} rows={2} /></label><label>Topic<select name="conceptId" defaultValue={row.concept_id}>{concepts.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Locator<input name="locator" defaultValue={row.source_locator} required /></label><label>Source description<input name="sourceDescription" defaultValue={row.source_description ?? ""} /></label><label>Teacher mark transcription<input name="teacherMark" defaultValue={row.teacher_mark ?? ""} /></label><button className="button" type="submit">Save new draft revision</button></form></details><form action={publishEvidence} className="review-form"><input type="hidden" name="evidenceId" value={row.id} /><label>After inspecting the fictional work, choose a local demo review result<select name="result" defaultValue="unclear"><option value="unclear">Unclear / no score</option><option value="correct">Correct</option><option value="incorrect">Incorrect</option></select></label><button className="secondary-button" type="submit">Publish reviewed evidence</button></form></>}
      {row.status === "reviewed" && <details><summary>Correct this reviewed observation</summary><p className="muted">A correction creates a new accepted revision; the old revision remains in history. Another tab must reload if this version changed.</p><form action={correctEvidence} className="form-card compact-form"><input type="hidden" name="evidenceId" value={row.id} /><input type="hidden" name="expectedRevisionId" value={row.revision_id} /><label>Question<textarea name="question" defaultValue={row.question_text} required rows={2} maxLength={1000} /></label><label>Response<textarea name="response" defaultValue={row.response} required rows={2} maxLength={2000} /></label><label>Topic<select name="conceptId" defaultValue={row.concept_id}>{concepts.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Locator<input name="locator" defaultValue={row.source_locator} required maxLength={200} /></label><label>Source description<input name="sourceDescription" defaultValue={row.source_description ?? ""} maxLength={200} /></label><label>Teacher mark transcription<input name="teacherMark" defaultValue={row.teacher_mark ?? ""} maxLength={100} /></label><label>Local review result<select name="result" defaultValue={row.mark ?? "unclear"}><option value="unclear">Unclear / no score</option><option value="correct">Correct</option><option value="incorrect">Incorrect</option></select></label><label>Reason for correction<input name="reason" required minLength={5} maxLength={300} placeholder="What changed in the reviewed record?" /></label><button className="secondary-button" type="submit">Save corrected revision</button></form></details>}
      <RevisionHistory db={db} evidenceId={row.id} />
    </article>)}</div>
  </div>;
}
